### ISSUE TITLE
Streaming URL used when using webhook

### ISSUE THREAD

**Issue by autotoxin** [wlbrough/clearbit-api#1]
When not setting enableStreaming() for the enrichment API (possibly others), it actually uses the streaming URL.

This line is the offender.
https://github.com/wlbrough/clearbit-api/blob/4f027d4daec6f74ec88fda58791987cd54c656bb/src/EnrichmentApi.php#L54
I think it should be 
`$streaming = $this->useStreaming ? '-streaming' : '';`

**Comment by GaryReckard** [comment]
Actually, it should be
```
$streaming = $this->useStreaming ? '-stream' : '';
```
according to the docs: https://clearbit.com/docs#streaming
